### ISSUE TITLE
First stable version 

### ISSUE THREAD

**Issue by abearab** [GilbertLabUCSF/ScreenPro2#1]
## Aims
- Python 3 stable version
- More detailed description and documentations about all analytical steps
- Improve statistical methods (e.g. FDR calculation, more complex analysis for drug combinations, etc.)
- Make it easier for users to run the pipeline
- Expand use cases to custom library designs
- Enable Exploratory Data Analysis (EDA) in Jupyter notebook

## To-do list
- [X] Set up the auto-generated documents – <https://screenpro2.readthedocs.io>.
  - [ ] #23
- [X] abearab/ScreenPro2#22
- [ ] #16 
- [ ] abearab/ScreenPro2#21 
- [x] Debug Python 3 scripts 
  - [x] #9 
  - [x] abearab/ScreenPro2#22 
  - [x] Use `pseudogenes` in phenoScore module **[hold]**
- [ ] #18
- [ ] Provide demo dataset and analysis for V2 and V3 library
- [ ] #10

___
## Future
- Building python [dash app](https://plotly.com/dash/) from a set of screens
- Compatibility with [CanDI](https://candi.readthedocs.io/)

**Comment by abearab** [comment]
This tool will be further developed at Arc Institute's GitHub – https://github.com/ArcInstitute/ScreenPro2
